# _config.yml

title: Shivani Agrawal
description: Software engineer focused on algorithm optimization at Google.
theme: minima
author:
  name: Shivani Agrawal
  email: your.email@example.com
  linkedin: https://www.linkedin.com/in/shivani-agrawal
  github: https://github.com/yourusername

# Enable GitHub Pages features
plugins:
  - jekyll-feed
